services:
  - type: web
    name: pib-chart-and-table
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
